### ISSUE TITLE
NPM install

### ISSUE THREAD

**Issue by vuxor** [NikolaGolubovic/uteam-api#4]
You have conflict  with your dependencies.
Please run npm install and fix your dep. versions.

**Comment by NikolaGolubovic** [comment]
sorry, i am not sure if it is on me to closed issues. 
anyway, i fixed them.

**Comment by vuxor** [comment]
I guess the fix is in pull req #5 ?

**Comment by NikolaGolubovic** [comment]
> I guess the fix is in pull req #5 ?

Yup! The newest pull will be without yarn(.lock) and packages incompatibilities

**Comment by vuxor** [comment]
I will take a look on that PR and leave comments there.
This issue can be closed.
